apiVersion: apps/v1
kind: Deployment

metadata:
 name: web
spec:
 replicas: 1
 selector:
   matchLabels:
     env: production
 template:
   metadata:
     name: myweb-image
     labels:
       env: production
   spec:
     containers:
     - name: web
       image: itvaibavsharma/httpd:latest
